In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense
from tensorflow.python.keras.wrappers.scikit_learn import KerasRegressor

In [34]:
"""
Age
Gender
Average miles driven per day
Personal debt
Monthly income
"""

df=pd.read_csv('car.csv')
df

age  gender  miles   debt  income  sales
0     28       0     23      0    4099    620
1     26       0     27      0    2677   1792
2     30       1     58  41576    6215  27754
3     26       1     25  43172    7626  28256
4     20       1     17   6979    8071   4438
..   ...     ...    ...    ...     ...    ...
958   22       0     11   8778    9829   1593
959   19       1     23   4850    3470   4742
960   28       1     28   9312    2720  12771
961   50       0     29  51343    8713  28511
962   47       1     15   3735    6406   6104

[963 rows x 6 columns]

In [35]:
Essentially, we are trying to predict the value of a potential car sale
(i.e. how much a particular person will spend on buying a car) 
for a customer based on the following attributes:


SyntaxError: invalid syntax (<ipython-input-35-dc380a4522d7>, line 1)

In [36]:
x=df.iloc[:,:-1]
x

age  gender  miles   debt  income
0     28       0     23      0    4099
1     26       0     27      0    2677
2     30       1     58  41576    6215
3     26       1     25  43172    7626
4     20       1     17   6979    8071
..   ...     ...    ...    ...     ...
958   22       0     11   8778    9829
959   19       1     23   4850    3470
960   28       1     28   9312    2720
961   50       0     29  51343    8713
962   47       1     15   3735    6406

[963 rows x 5 columns]

In [37]:
y=df.iloc[:,-1].values
y

array([  620,  1792, 27754, 28256,  4438,  2102,  8520,   500, 22997,
       26517, 14112, 20956,  7650,  3197,  4531, 18005, 22854, 10278,
         739,  4271,  4733,   971,  6263, 24677, 22830,  9913,  3598,
        5222, 22450, 24993, 28607, 16875,  3199, 25394, 11562,  4376,
       11530,   780,  2945,  7601, 15044,  2073,  2869,  1492,  5927,
        3454,  2282, 17374, 20341,  7062, 27677, 12581, 10780, 15288,
        3928,  3852, 18819,  1447, 15573, 25996, 14202, 24097, 21708,
       14074, 21608,  3453,  6376, 20247, 22842,  5018,   648,  2454,
       27800,  2531,  1205, 16653, 28822, 24291, 12748, 15905,  5489,
       26152,  4785,  6465,  6200,  4923, 29715, 20532, 23645, 22508,
       24130,  1432, 27213,  7388,  5580, 24161, 24583,  7274,  3978,
        8082, 27667, 18965, 23883,  1206, 19606, 19634,  4298,  9851,
       27777,  3310,  2228,  9834, 13699, 21242, 14133, 24203,  2327,
       26141, 19173,  3433, 10369, 25664,  9041,  1712, 18655, 11119,
        7165, 21376,

In [38]:
scaler_x = MinMaxScaler()
print(scaler_x.fit(x))
xscale=scaler_x.transform(x)


MinMaxScaler()


In [39]:
y=np.reshape(y, (-1,1))
scaler_y = MinMaxScaler()
print(scaler_y.fit(y))
yscale=scaler_y.transform(y)

MinMaxScaler()


In [40]:
xscale

array([[0.2195122 , 0.        , 0.14942529, 0.        , 0.34243943],
       [0.17073171, 0.        , 0.1954023 , 0.        , 0.22364244],
       [0.26829268, 1.        , 0.55172414, 0.6955998 , 0.5192147 ],
       ...,
       [0.2195122 , 1.        , 0.20689655, 0.15579722, 0.22723475],
       [0.75609756, 0.        , 0.2183908 , 0.85900954, 0.72790309],
       [0.68292683, 1.        , 0.05747126, 0.06248954, 0.53517126]])

In [41]:
yscale

array([[4.07802624e-03],
       [4.39067491e-02],
       [9.26187725e-01],
       [9.43247468e-01],
       [1.33827228e-01],
       [5.44416502e-02],
       [2.72548087e-01],
       [0.00000000e+00],
       [7.64527968e-01],
       [8.84150071e-01],
       [4.62584109e-01],
       [6.95167539e-01],
       [2.42982397e-01],
       [9.16536396e-02],
       [1.36987698e-01],
       [5.94882077e-01],
       [7.59668321e-01],
       [3.32291171e-01],
       [8.12206892e-03],
       [1.28151974e-01],
       [1.43852375e-01],
       [1.60062530e-02],
       [1.95847210e-01],
       [8.21620336e-01],
       [7.58852715e-01],
       [3.19887175e-01],
       [1.05281044e-01],
       [1.60470332e-01],
       [7.45938966e-01],
       [8.32359138e-01],
       [9.55175695e-01],
       [5.56480663e-01],
       [9.17216067e-02],
       [8.45986543e-01],
       [3.75926052e-01],
       [1.31720247e-01],
       [3.74838578e-01],
       [9.51539455e-03],
       [8.30897845e-02],
       [2.41317202e-01],


In [45]:

# Split the data for training and testing
train_x, test_x, train_y, test_y = train_test_split(xscale, yscale, test_size=0.20)


In [46]:


# Build the model

model = Sequential()

model.add(Dense(12, input_shape=(5,),kernel_initializer='normal', activation='relu', name='fc1'))
model.add(Dense(8, activation='relu', name='fc2'))
model.add(Dense(1, activation='linear', name='output'))
#n1-vers=0.1    n2-verg=0.2   n3-setosa=0.7
# Adam optimizer with learning rate of 0.001

model.compile(optimizer='adam', loss='mse', metrics=['mae'])

print('Neural Network Model Summary: ')
print(model.summary())


Neural Network Model Summary: 
Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
fc1 (Dense)                  (None, 12)                72        
_________________________________________________________________
fc2 (Dense)                  (None, 8)                 104       
_________________________________________________________________
output (Dense)               (None, 1)                 9         
Total params: 185
Trainable params: 185
Non-trainable params: 0
_________________________________________________________________
None


In [47]:

# Train the model
model.fit(train_x, train_y, verbose=2, batch_size=5, epochs=100)

# Test on unseen data

results = model.evaluate(test_x, test_y)

print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

Epoch 1/100
154/154 - 0s - loss: 0.0717 - mae: 0.2141
Epoch 2/100
154/154 - 0s - loss: 0.0204 - mae: 0.1176
Epoch 3/100
154/154 - 0s - loss: 0.0166 - mae: 0.1017
Epoch 4/100
154/154 - 0s - loss: 0.0162 - mae: 0.0990
Epoch 5/100
154/154 - 0s - loss: 0.0162 - mae: 0.0986
Epoch 6/100
154/154 - 0s - loss: 0.0160 - mae: 0.0975
Epoch 7/100
154/154 - 0s - loss: 0.0158 - mae: 0.0965
Epoch 8/100
154/154 - 0s - loss: 0.0158 - mae: 0.0963
Epoch 9/100
154/154 - 0s - loss: 0.0157 - mae: 0.0961
Epoch 10/100
154/154 - 0s - loss: 0.0154 - mae: 0.0948
Epoch 11/100
154/154 - 0s - loss: 0.0153 - mae: 0.0941
Epoch 12/100
154/154 - 0s - loss: 0.0156 - mae: 0.0959
Epoch 13/100
154/154 - 0s - loss: 0.0148 - mae: 0.0929
Epoch 14/100
154/154 - 0s - loss: 0.0146 - mae: 0.0919
Epoch 15/100
154/154 - 0s - loss: 0.0144 - mae: 0.0915
Epoch 16/100
154/154 - 0s - loss: 0.0141 - mae: 0.0906
Epoch 17/100
154/154 - 0s - loss: 0.0140 - mae: 0.0901
Epoch 18/100
154/154 - 0s - loss: 0.0136 - mae: 0.0888
Epoch 19/100
154/15

In [50]:
results

[0.013498270884156227, 0.0847734734416008]

In [49]:
plt.plot(results.history['loss'])
plt.plot(results.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'validation'], loc='upper left')
plt.show()

AttributeError: 'list' object has no attribute 'history'